---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
date: "2023-03-06"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

path <- "/Users/mayahsu/Desktop/school/environmental data science/esp106_Maya_Hsu/"

knitr::opts_knit$set(root.dir = path)
setwd(path)
library(tidyverse)
library(tidyr)
library(ggplot2)
housing <- read.csv("ACSCP1Y2021.CP04-2023-03-15T072503.csv")
projected <- read.csv("table-a-housing-development-applications-submitted.csv")
demographic <- read.csv("county data.csv")
```

```{r}
housing <- t(housing) #transposing the data

headers <- housing[1, ] #extracted values from row 1 as a vector 
colnames(housing) <- headers #renamed columns with row 1 values
housing <- housing[-1, ] #removed first row
housing <- housing[-165, ]
```

```{r}
Years <- c("2021", "2019", "2018", "2017") #creating list of dates
Years <- rep(Years, 41) #repeating dates
Years
as.data.frame(Years) #data frame
housing <- cbind(housing, Years) #adding dates to housing data
```

```{r}
County <- rownames(housing)
County <- substr(County, 1, nchar(County)-34)
as.data.frame(County)
County <- gsub(".", " ", County, fixed = TRUE)
rownames(housing) <- 1:nrow(housing)

housing <- gsub("N", NA, housing)
housing <- gsub("(X)", NA, housing)

housing <- cbind(housing, County)
```

```{r}
housing_type <- housing[ ,c(9:17)]
housing_type <- gsub("%", "", housing_type, fixed = TRUE)
housing_type <- as.data.frame(housing_type)
housing_type <- sapply(housing_type, as.numeric)
housing_type <- housing_type/100

housing_type <- as.data.frame(housing_type)

housing_type <- cbind(housing_type, housing[ ,161:162])
```

#Bay Area graph
```{r}
h2021 <- subset(housing_type, Years == "2021")
bay <- subset(h2021, County %in% c("SAN FRANCISCO", "SANTA CLARA", "MARIN", "ALAMEDA", "SOLANO", "CONTRA COSTA", "NAPA", "SONOMA", "SAN MATEO"))
names_bay <- bay[, 11]
bay <- subset(bay, select = -c(10, 11))

color <- c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6')

bay <- as.matrix(bay)
bay <- t(bay)

par(mar=c(5.1,6,6,6)+.1, xpd = TRUE)
barplot(bay, horiz = TRUE, names.arg = names_bay, cex.names = 0.7, las = 1, col = color, main = "Housing Type by County in the Bay Area", xlab = "Proportion")
legend("right", inset = -0.28, legend = rownames(bay), fill = color, cex = 0.5, title = "Housing Type")
```

#Metro graph
```{r}
housing_type_2021 <- subset(housing_type, Years == "2021")
housing_type_metros <- subset(housing_type_2021, County %in% c("SAN FRANCISCO", "LOS ANGELES", "SAN DIEGO", "SACRAMENTO"))
names_metros <- housing_type_metros[, 11]
housing_type_metros <- subset(housing_type_metros, select = -c(10, 11))

color <- c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6')

housing_type_metros <- as.matrix(housing_type_metros)
housing_type_metros <- t(housing_type_metros)

par(mar=c(5.1,6,6,6)+.1, xpd = TRUE)
barplot(housing_type_metros, horiz = TRUE, names.arg = names_metros, cex.names = 0.7, las = 1, col = color, main = "Housing Type by County", xlab = "Proportion")
legend("right", inset = -0.28, legend = rownames(housing_type_metros), fill = color, cex = 0.5, title = "Housing Type")
```

```{r}
projected$CNTY_NAME <- str_to_title(projected$CNTY_NAME)
#projects that where approved with SB35
i = projected$APP_SUBMITTED_SB35 == "Yes-Approved"
SB35 <- projected[i,]
#projects that have occupets 
i = SB35$CO_ISSUE_DT1 != ""
OC_sb35 <- SB35[i,]
```

```{r}
counties <- unique(SB35$CNTY_NAME)
counties <- sort(counties)
```

```{r}
h2021 <- subset(housing_type, Years == "2021")
sb35_housing_type <- subset(h2021, County %in% counties)
names_sb35 <- sb35_housing_type[, 11]
sb35_housing_type <- subset(sb35_housing_type, select = -c(10, 11))

color <- c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6')

sb_type <- colnames(sb35_housing_type)
sb_type <- str_squish(sb_type)

sb35_housing_type <- as.matrix(sb35_housing_type)
sb35_housing_type <- t(sb35_housing_type)

#png(filename = "/Users/mayahsu/Desktop/school/environmental data science/final/Current Housing Data", width = 5, height = 5, units = "in", res = 300)
par(mar=c(4,5,5,5)+.1, xpd = TRUE)
barplot(sb35_housing_type, horiz = TRUE, names.arg = names_sb35, cex.names = 0.4, las = 1, col = color, main = "Housing Type in Counties With\nApproved SB35 Projects", xlab = "Proportion", cex.axis = 0.5, width = 1, cex.lab = 0.7, xlim = c(0,1), ylim = c(0, 32))
legend("right", inset = -0.19, legend = sb_type, fill = color, cex = 0.5, title = "Housing Type")
#dev.off()
```

```{r}
SB35_agg <- aggregate(SB35[, 29:35], by = list(SB35$CNTY_NAME), sum)

units <- aggregate(SB35[, 20], by = list(SB35$CNTY_NAME), sum) #number of sb35 units approved
colnames(units) <- c("County", "Units")

#sb35_per_county <- as.data.frame(SB35_agg[ ,1])
#count <- table(SB35$CNTY_NAME)
#count <- as.data.frame(count)
#total <- count$Freq
#sb35_per_county <- cbind(sb35_per_county, total)
#colnames(sb35_per_county) <- c("County", "Total")

sub <- housing[ , c(2, 161, 162)]
#sub <- subset(sub, County %in% SB35_agg[ ,1])
sub <- as.data.frame(sub)
sub <- sub[-c(146, 147, 164), ]
sub[ ,1] <- gsub(",", "", sub[ ,1], fixed = TRUE)
sub[ ,1:2] <- sapply(sub[ ,1:2], as.numeric)

sub <- subset(sub, Years == 2017 | Years == 2021)
colnames(sub) <- c("Total Housing Units", "Year", "County")

sub <- pivot_wider(sub, names_from = "Year", values_from = "Total Housing Units")
sub[ ,4] <- (sub[ ,2]-sub[ ,3])/sub[ ,3]
colnames(sub) <- c("County", "2021",  "2017", "Percent Change in Housing")

change_v_sb35 <- merge(sub, units, by = "County")
change_v_sb35 <- merge(change_v_sb35, approved_v_income, by = "County")

library(ggplot2)
ggplot(change_v_sb35, aes(x = change_v_sb35[ ,4], y = change_v_sb35[ ,9]))+
  geom_point()+geom_smooth(method = "lm")+
  labs(x = "Percent Change in Total Housing", y = "Number of Approved SB35 Projects")

cor.test(change_v_sb35[ ,4], change_v_sb35[ ,9])
```

```{r}
new_type <- as.data.frame(projected[ ,c(2, 9)])
new_type <- pivot_wider(new_type, names_from = UNIT_CAT, values_from = CNTY_NAME)

table(projected$CNTY_NAME)
rownames(new_type) <- new_type[ ,1]
new_type[ ,1] <- NULL
ggplot(new_type, aes(x = ))
```

```{r}
i <- (projected$TENURE_DESC == "Owner")&(projected$UNIT_CAT_DESC != "Single-Family Detached Unit")
table(i)

#compare low income developments to poverty rates by county
```

```{r}
med_income <- as.data.frame(demographic[ ,c(1,2,29)])
med_income <- med_income[-c(59,60), ]
colnames(med_income) <- c("County", "Population","Median Income")

income <- med_income[ ,3]
income <- gsub("$", "", income, fixed = TRUE)
income <- gsub(" ", "", income, fixed = TRUE)
income <- gsub(",", "", income, fixed = TRUE)
income <- as.data.frame(income)
income <- sapply(income, as.numeric)
med_income[ ,3] <- income

population <- med_income[ ,2]
population <- gsub(",", "", population, fixed = TRUE)
population <- as.data.frame(population)
population <- sapply(population, as.numeric)
med_income[ ,2] <- population

approved_v_income <- merge(units, med_income, by = "County")
approved_v_income[ ,5] <- approved_v_income[ ,2]/approved_v_income[ ,3]
colnames(approved_v_income) <- c("County", "Count", "Population", "Median Income", "Units/Person")

ggplot(approved_v_income, aes(x = approved_v_income[ ,4], y = approved_v_income[ ,5]))+
  geom_point()+geom_smooth(method = "lm")+
  labs(x = "Median Income", y = "SB35 Projects per Person")

cor.test(approved_v_income[ ,4], approved_v_income[ ,5])
```
